# Main navigation menu
[[main]]
  name = "Home"
  url = "/"
  weight = 1
  identifier = "home"

[[main]]
  name = "Categories"
  url = "/categories/"
  weight = 2
  identifier = "categories"

[[main]]
  name = "About"
  url = "/about/"
  weight = 3

[[main]]
  name = "Contact"
  url = "/contact/"
  weight = 4

# Social media links (will appear as icons in header)
[[social]]
  name = "github"
  url = "https://github.com/Coutons"
  weight = 1

[[social]]
  name = "twitter"
  url = "https://twitter.com/CoursesGift"
  weight = 2

[[social]]
  name = "youtube"
  url = "https://youtube.com/@courseswyn"
  weight = 3

[[social]]
  name = "rss"
  url = "/index.xml"
  weight = 4
