# Main navigation menu
[[main]]
  name = "Home"
  url = "/"
  weight = 1
  identifier = "home"

[[main]]
  name = "Courses"
  url = "/courses/"
  weight = 2
  identifier = "courses"

[[main]]
  name = "Categories"
  url = "/categories/"
  weight = 3
  identifier = "categories"

# Footer menu
[[footer]]
  name = "About"
  url = "/about/"
  weight = 1

[[footer]]
  name = "Contact"
  url = "/contact/"
  weight = 2

[[footer]]
  name = "Privacy Policy"
  url = "/privacy/"
  weight = 3

[[footer]]
  name = "Terms of Service"
  url = "/terms/"
  weight = 4

# Social media links
[[social]]
  name = "github"
  url = "https://github.com/Coutons"
  weight = 1

[[social]]
  name = "twitter"
  url = "https://twitter.com/CoursesGift"
  weight = 2

[[social]]
  name = "youtube"
  url = "https://youtube.com/@courseswyn"
  weight = 3

[[social]]
  name = "rss"
  url = "/index.xml"
  weight = 4
