# Social media links
[[social]]
  name = "github"
  url = "https://github.com/Coutons"
  weight = 1
  icon = "github"

[[social]]
  name = "twitter"
  url = "https://twitter.com/CoursesGift"
  weight = 2
  icon = "twitter"

[[social]]
  name = "youtube"
  url = "https://youtube.com/@courseswyn"
  weight = 3
  icon = "youtube"

[[social]]
  name = "rss"
  url = "/index.xml"
  weight = 4
  icon = "rss"
